// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmPI2gLl_h6xoC2wTwhg3u76u27fOj-bI',
    appId: '1:267982853281:web:8c827880ccbf91dad1cce0',
    messagingSenderId: '267982853281',
    projectId: 'airbound-e1a16',
    authDomain: 'airbound-e1a16.firebaseapp.com',
    storageBucket: 'airbound-e1a16.firebasestorage.app',
    measurementId: 'G-0MN93H6XNG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfMj_y_YOrtUxRTMpE5YtJTD14vxsKUDI',
    appId: '1:267982853281:android:b8b8c7dac5287927d1cce0',
    messagingSenderId: '267982853281',
    projectId: 'airbound-e1a16',
    storageBucket: 'airbound-e1a16.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4i5WQsb8_oVlZg6rriMnJFdHOiYcVCnY',
    appId: '1:267982853281:ios:2b4ef1e358ac4053d1cce0',
    messagingSenderId: '267982853281',
    projectId: 'airbound-e1a16',
    storageBucket: 'airbound-e1a16.firebasestorage.app',
    iosBundleId: 'com.example.airbound',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4i5WQsb8_oVlZg6rriMnJFdHOiYcVCnY',
    appId: '1:267982853281:ios:2b4ef1e358ac4053d1cce0',
    messagingSenderId: '267982853281',
    projectId: 'airbound-e1a16',
    storageBucket: 'airbound-e1a16.firebasestorage.app',
    iosBundleId: 'com.example.airbound',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmPI2gLl_h6xoC2wTwhg3u76u27fOj-bI',
    appId: '1:267982853281:web:21ca0a4ac326d938d1cce0',
    messagingSenderId: '267982853281',
    projectId: 'airbound-e1a16',
    authDomain: 'airbound-e1a16.firebaseapp.com',
    storageBucket: 'airbound-e1a16.firebasestorage.app',
    measurementId: 'G-CJMJ3DKT1T',
  );

}